services:
  mininet:
    container_name: onos-mininet
    image: davidlin123/mininet:latest
    privileged: true
    network_mode: host
    tty: true
    stdin_open: true
    volumes:
      - /lib/modules:/lib/modules
      - ./topologies:/root/topologies

  onos:
    container_name: onos-controller
    image: onosproject/onos:latest
    ports:
      - "8181:8181"  # REST API and GUI
      - "6653:6653"  # OpenFlow
      - "8101:8101"  # ONOS CLI
      - "9876:9876"  # ONOS clustering
    environment:
      - ONOS_APPS=gui2,drivers,openflow,fwd,intent

  agent:
    container_name: onos-agent
    build:
      context: ./agents
      dockerfile: Dockerfile
    profiles:
      - donotstart
    volumes:
      - ./agents:/app
    env_file:
      - ./agents/.env
