services:
  mininet:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mininet
    privileged: true
    stdin_open: true
    tty: true
    network_mode: "host"
    volumes:
      - /lib/modules:/lib/modules
    command: ["tail", "-f", "/dev/null"]

  onos:
    container_name: onos-controller
    image: onosproject/onos:latest
    ports:
      - "8181:8181"  # REST API and GUI
      - "6653:6653"  # OpenFlow
      - "8101:8101"  # ONOS CLI
      - "9876:9876"  # ONOS clustering
    environment:
      - ONOS_APPS=gui2,drivers,openflow,proxyarp
